#!/bin/bash

scriptname="setup.zsh"

if [ -f "$scriptname" ]; then
    rm -f "$scriptname"
fi

{
    echo "#!/bin/zsh"
    echo '
####################################################################################################
#                    WARNING: THIS FILE IS AUTOMATICALLY GENERATED BY A SCRIPT.                    #
#                           ANY MANUAL MODIFICATIONS MAY BE OVERWRITTEN                            #
####################################################################################################
'
    cat ./v2/scripts/start.zsh
    find ./v2/functions -type f -print0 | xargs -0 cat
    cat ./v2/scripts/main.zsh
} > "$scriptname"
