#!/bin/bash

scriptname="setup.zsh"

if [ -f "$scriptname" ]; then
    rm -f "$scriptname"
fi

{
    echo "#!/bin/zsh"
    echo '
####################################################################################################
#                    WARNING: THIS FILE IS AUTOMATICALLY GENERATED BY A SCRIPT.                    #
#                           ANY MANUAL MODIFICATIONS MAY BE OVERWRITTEN                            #
####################################################################################################
'
    cat scripts/start.zsh
    for file in functions/*.zsh; do
        # Voeg elk bestand toe aan setup.zsh
        cat "$file"
    done
    cat scripts/main.zsh
} >"$scriptname"

# Define prompt_robot function (from functions/prompts.zsh)
source functions/prompts.zsh

# Define the robot character and colors (from scripts/start.zsh)
source scripts/start.zsh

# Function to add a section to setup.zsh
add_section() {
  local section_name=$1
  echo "# $section_name" >> setup.zsh
  echo "" >> setup.zsh
}

# Function to add a prompt to setup.zsh
add_prompt() {
  local prompt_message=$1
  local command_to_run=$2
  if prompt_robot "$prompt_message"; then
    echo "$command_to_run" >> setup.zsh
  fi
}

# Start building setup.zsh
echo "#!/bin/zsh" >> setup.zsh
echo "# This is an automatically generated script" >> setup.zsh

# Add your categories here (e.g., Homebrew installation)
add_section "Homebrew Installation"
add_prompt "Install Homebrew?" "/bin/bash -c \"\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)\""

# Add another category (e.g., Finder preferences)
add_section "Finder Preferences"
add_prompt "Customize Finder preferences?" "set_finder_preferences"

# You can add more categories and prompts as needed

# Make the script executable
chmod +x setup.zsh
