name: Build on Linux

on:
  push:
    branches:
      - main
      - v0.*

jobs:
  build-runspace:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Run Build Script
      run: |
        chmod +x build.zsh
        ./build.sh
      shell: bash
    - name: Commit Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Compile setup.zsh"
        git push
      shell: bash
