name: Build on Linux

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Set up Zsh
      run: |
        sudo apt-get update
        sudo apt-get install zsh
      shell: bash

    - name: Build Script
      run: |
        chmod +x build_script.sh
        ./build_script.sh
